### ISSUE TITLE
unable to play videos with special characters in the file name

### ISSUE THREAD

**Issue by nklogicQA** [nirmalyakar/video-player-script-generator#4]
unable to play videos with special characters in the file name.
![SpecialCharacter](https://user-images.githubusercontent.com/37267280/62491244-ebed3d80-b7e8-11e9-9278-dd0479702d9f.png)

**Comment by nirmalyakar** [comment]
fixed in version 1.3.1

**Comment by nirmalyakar** [comment]
fixed in version 1.3.1
